# Generated by Django 4.2.2 on 2023-07-27 08:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='public_date',
            field=models.DateTimeField(default=datetime.date(2023, 7, 27)),
        ),
    ]
